name: Explorer Application
description: Use this form to apply as a Explorer to the Fuel Developer Champions program.
title: "[Application] : "
labels: ["application"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit an application to the Fuel Developer Champions program as a Explorer! Explorers are developers who have begun building on Fuel and are looking to join a community of other developers to learn from and share their knowledge with. We are excited to have you join us!
  - type: markdown
    attributes:
      value: |
        Please fill out each section to the best of your ability. The more information you can provide the better we are able to evaluate your
        application.
  - type: textarea
    id: proof-of-code
    attributes:
      label: Proof of your code
      description: Share with us the links to GitHub repos where you have been a code contributor for more than one instance to a merged pull request in the past three months in a web3 project, preferably but not exclusively a Fuel project.
      placeholder: Add links to your code contribution(s) here.
  - type: textarea
    id: proof-of-project
    attributes:
      label: Fuel projects you have worked on
      description: Share with us the links to GitHub repos of Fuel projects you have actively contributed to in the past three months.
      placeholder: Add links to your Fuel project contribution(s) here.
  - type: textarea
    id: fuel-forum-activity
    attributes:
      label: Activity on the Fuel forum
      description: | 
        Share with us the link to your Fuel Discourse forum (https://forum.fuel.network) profile. We will look to see for the following:
        - You have been active on the forum in the past 3 months
        - What kind of activity you have on the forum in that time, e.g. asking questions, helping others, etc.
      placeholder: Add links to your forum profile here.
  - type: textarea
    id: proof-of-content-creation
    attributes:
      label: Proof of content creation
      description: | 
        Share with us links to any content you have created in the past three months that is related to Fuel. This can include blog posts, videos, podcasts, etc.
      placeholder: Add links to your content here.
  - type: textarea
    id: social-media-links
    attributes:
      label: Links to your social media profiles
      description: | 
        Share with us links to any social media profiles you may have on web3 or web2.
      placeholder: Add links to your social media profiles here.
  - type: dropdown
    id: current-member
    attributes:
      label: Current Champions member
      description: Are you a current member of the Fuel Developer Champions program?
      options:
        - "Yes, I'm a Pioneer and applying to level up to Explorer"
        - "No, I'm not a Fuel Developer Champion yet"
  - type: dropdown
    id: ambassador-program
    attributes:
      label: Fuel Ambassador Program
      description: Are you a current Fuel Ambassador?
      options:
        - "Yes, I'm a Fuel Ambassador"
        - "No, I'm not a Fuel Ambassador"
  - type: checkboxes
    id: code-of-conduct-agreement
    attributes:
      label: Code of Conduct Agreement
      description: I have read and agree to the [Fuel Developer Champions Code of Conduct](https://github.com/fuel-champions/code-of-conduct).
      options:
      - label: I agree to follow the Code of Conduct
        required: true
